stages:
  - build
  - test
  - review
  - stage
  - production

variables:
  DATABASE_URL: 'mongodb://mongo/user_posts'

before_script:
  - cd reddit
  - bundle install 

build_job:
  before_script: 
    - cd docker-monolith
  stage: build
  tags:
    - shell
  script:
    - echo "Building Reddit Container"
    - docker build -t $DOCKER_USER/gitlab_hw:$CI_PIPELINE_ID .
    - docker login -u $DOCKER_USER -p $DOCKER_USER_PASSWORD
    - docker push $DOCKER_USER/gitlab_hw:$CI_PIPELINE_ID

test_unit_job:
  stage: test
  when: manual
  services:
    - mongo:latest
  script:
    - ruby simpletest.rb

test_integration_job:
  before_script:
    - echo 'Gcloud testing'
  stage: test
  script:
    - echo 'Testing 2'

deploy_dev_job:
  stage: review
  tags:
    - gcp
  script:
    - echo 'Deploy'
    - echo $GCLOUD_SERVICE_ACCOUNT_KEY > ./$CI_PIPELINE_ID.json
    - gcloud auth activate-service-account --key-file=./$CI_PIPELINE_ID.json
    - gcloud compute ssh gitlab-ci --force-key-file-overwrite --zone $GCP_ZONE --command "sudo docker run --rm -d --name reddit -p 9292:9292 $DOCKER_USER/gitlab_hw:$CI_PIPELINE_ID"
  environment:
    name: dev
    url: http://$CI_SERVER_HOST:9292

branch review:
  stage: review
  script: echo "Deploy to $CI_ENVIRONMENT_SLUG"
  environment:
    name: branch/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.example.com
  only:
    - branches
  except:
    - master

staging:
  stage: stage
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: stage
    url: https://beta.example.com

production:
  stage: production
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: production
    url: https://example.com
