stages:
  - build
  - test
  - review
  - stage
  - production

variables:
  DATABASE_URL: 'mongodb://mongo/user_posts'

before_script:
  - cd reddit
  - bundle install 

build_job:
  before_script: 
    - cd docker-monolith
  stage: build
  image: ubuntu:16.04
  script:
    - apt-get update
    - apt-get install -y mongodb-server ruby-full ruby-dev build-essential git
    - gem install bundler
    - git clone -b monolith https://github.com/express42/reddit.git
    - cp mongod.conf /etc/mongod.conf
    - cd /reddit && bundle install
    - /usr/bin/mongod --fork --logpath /var/log/mongod.log --config /etc/mongodb.conf
    - source DATABASE_URL=127.0.0.1
    - puma
  environment:
    name: $CI_COMMIT_REF_NAME
    url: http://$CI_SERVER_HOST:9292
  only:
    - branches

test_unit_job:
  stage: test
  services:
    - mongo:latest
  script:
    - ruby simpletest.rb

test_integration_job:
  stage: test
  script:
    - echo 'Testing 2'

deploy_dev_job:
  stage: review
  script:
    - echo 'Deploy'
  environment:
    name: dev
    url: http://dev.example.com

branch review:
  stage: review
  script: echo "Deploy to $CI_ENVIRONMENT_SLUG"
  environment:
    name: branch/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.example.com
  only:
    - branches
  except:
    - master

staging:
  stage: stage
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: stage
    url: https://beta.example.com

production:
  stage: production
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: production
    url: https://example.com
