dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-02/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: EIvsWxiskgZT21oO7Uk5o6ErUSH8LMeSGblgvmU/+R6BDGXh8Wj5QysNR+3sd3SG9lx4f/hb8GmpRjFh/Gck3NOCbR/1Ti/PbTmAGA0wBYerSbq+M0/cACEXl3tCnaMhDVvStWzOCR7W4AK5AEZRusT/BcOpbq4aJUTwQfdBqUp3s/ElMWCIFddKfSk0t5n7p6f9ULoPe5G7QiUvkTLJ/NYhHCMa1AnEMBXIV1C9rySS/6HbWAB8J9iaT+jHzIiwnBsAUs8giOLvSS0h/ex1UJgqkI2vZ48JvZYibeHIpJMyNrvmR5yIZn2WRpgxpDjBqV7jp9JCbWk+LQoFFG1IlPDN76p6mLHCQ+6SyXlg4XMS3VJNzjkaHHmKVDLydZQj2jVRJRDyrAcgG6862xLWkgf17J/PjgbPUZpbYu8tumGSxGLHbg4hgE/csB2LMme8R2UUPDpuFBlci+52EKlCUYw59MAmLKrDOSteSULKNHf0+pjfpi47QLjeNh/ZGRCWtFC1Jte2qRcJ0OLbS5bvxrBGD74U7knb42XuX2G/8srODje63J45RBgd1JizjG1/AV1R9F1QgGhles33rTYAPq5djQiSUvM5BBNccas5hg2rx/Cnk10eFmkPqoT36NktrqyNI7KgIE0Lj0T66iXJGE+wPPROlLlqNzjGI6/Njcw=
