global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: 'otus_homework'
