version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_VERSION}
    volumes:
      - ./src/post_db:/data/db
    networks:
      reddit:
        aliases:
          - comment_db
          - post_db
  ui:
    image: ${USER_NAME}/ui:${UI_VERSION}
    ports:
      - ${UI_PORT}:${REDDIT_PORT}/tcp
    networks:
      - ui
  post:
    image: ${USER_NAME}/post:${POST_VERSION}
    networks:
      - reddit
      - ui
  comment:
    image: ${USER_NAME}/comment:${COMMENT_VERSION}
    networks:
      - reddit
      - ui

volumes:
  post_db:
  prometheus_data:  

networks:
  reddit:
  ui:
